### ISSUE TITLE
线上的服务目前量大了发现个问题：can't identify protocol

### ISSUE THREAD

**Issue by magicgaro** [swoole/framework#105]
lsof 主进程号发现大量的
php     5679 root 1683u  sock                0,6      0t0 1025004457 can't identify protocol
php     5679 root 1684u  sock                0,6      0t0 1024992970 can't identify protocol
php     5679 root 1685u  sock                0,6      0t0 1024986701 can't identify protocol
php     5679 root 1686u  sock                0,6      0t0 1024996014 can't identify protocol
php     5679 root 1687u  sock                0,6      0t0 1024998498 can't identify protocol
php     5679 root 1688u  sock                0,6      0t0 1025001525 can't identify protocol
php     5679 root 1689u  sock                0,6      0t0 1025010695 can't identify protocol
php     5679 root 1690u  sock                0,6      0t0 1025013662 can't identify protocol
php     5679 root 1691u  sock                0,6      0t0 1025007642 can't identify protocol
php     5679 root 1692u  sock                0,6      0t0 1025028939 can't identify protocol
php     5679 root 1693u  sock                0,6      0t0 1025016683 can't identify protocol
php     5679 root 1694u  sock                0,6      0t0 1025019838 can't identify protocol
php     5679 root 1695u  sock                0,6      0t0 1025026176 can't identify protocol
php     5679 root 1696u  sock                0,6      0t0 1025022972 can't identify protocol
php     5679 root 1697u  sock                0,6      0t0 1025037654 can't identify protocol
php     5679 root 1698u  sock                0,6      0t0 1025031907 can't identify protocol
php     5679 root 1699u  sock                0,6      0t0 1025034665 can't identify protocol
php     5679 root 1700u  sock                0,6      0t0 1025043423 can't identify protocol
php     5679 root 1701u  sock                0,6      0t0 1025040482 can't identify protocol
php     5679 root 1702u  sock                0,6      0t0 1025049331 can't identify protocol
php     5679 root 1703u  sock                0,6      0t0 1025052197 can't identify protocol
php     5679 root 1704u  sock                0,6      0t0 1025046323 can't identify protocol
php     5679 root 1705u  sock                0,6      0t0 1025055235 can't identify protocol
时间长了有上万个 导致有时候资源耗尽

strace

accept4(87, 0x7ffff9738130, [16], SOCK_CLOEXEC|SOCK_NONBLOCK) = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=86, events=POLLIN}, {fd=87, events=POLLIN}], 2, 1000) = 1 ([{fd=87, revents=POLLIN}])
accept4(87, {sa_family=AF_INET, sin_port=htons(33659), sin_addr=inet_addr("127.0.0.1")}, [16], SOCK_CLOEXEC|SOCK_NONBLOCK) = 1919
epoll_ctl(91, EPOLL_CTL_ADD, 1919, {EPOLLOUT, {u32=1919, u64=1919}}) = 0
accept4(87, 0x7ffff9738130, [16], SOCK_CLOEXEC|SOCK_NONBLOCK) = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=86, events=POLLIN}, {fd=87, events=POLLIN}], 2, 1000) = 1 ([{fd=87, revents=POLLIN}])
accept4(87, {sa_family=AF_INET, sin_port=htons(33660), sin_addr=inet_addr("127.0.0.1")}, [16], SOCK_CLOEXEC|SOCK_NONBLOCK) = 1918
epoll_ctl(89, EPOLL_CTL_ADD, 1918, {EPOLLOUT, {u32=1918, u64=1918}}) = 0
accept4(87, 0x7ffff9738130, [16], SOCK_CLOEXEC|SOCK_NONBLOCK) = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=86, events=POLLIN}, {fd=87, events=POLLIN}], 2, 1000) = 1 ([{fd=87, revents=POLLIN}])
accept4(87, {sa_family=AF_INET, sin_port=htons(33661), sin_addr=inet_addr("127.0.0.1")}, [16], SOCK_CLOEXEC|SOCK_NONBLOCK) = 1922
epoll_ctl(89, EPOLL_CTL_ADD, 1922, {EPOLLOUT, {u32=1922, u64=1922}}) = 0
accept4(87, 0x7ffff9738130, [16], SOCK_CLOEXEC|SOCK_NONBLOCK) = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=86, events=POLLIN}, {fd=87, events=POLLIN}], 2, 1000) = 1 ([{fd=87, revents=POLLIN}])
accept4(87, {sa_family=AF_INET, sin_port=htons(33662), sin_addr=inet_addr("127.0.0.1")}, [16], SOCK_CLOEXEC|SOCK_NONBLOCK) = 1918
epoll_ctl(89, EPOLL_CTL_ADD, 1918, {EPOLLOUT, {u32=1918, u64=1918}}) = 0
accept4(87, 0x7ffff9738130, [16], SOCK_CLOEXEC|SOCK_NONBLOCK) = -1 EAGAIN (Resource temporarily unavailable)

**Comment by matyhtf** [comment]
1. 建议前置`Nginx`
2. 调大`ulimit -n`的值
3. 开启空闲连接剔除的设置 `heartbeat_idle_time`
