### ISSUE TITLE
用1.8.1的扩展时websocket client连接不了

### ISSUE THREAD

**Issue by xiangxn** [swoole/framework#112]
object(Swoole\Http\WebSocketFrame)#27 (8) {
  ["finish"]=>
  bool(true)
  ["opcode"]=>
  int(8)
  ["data"]=>
  string(38) "�Clients may not send unmasked frames"
  ["length"]=>
  int(38)
  ["rsv1"]=>
  int(0)
  ["rsv2"]=>
  int(0)
  ["rsv3"]=>
  int(0)
  ["mask"]=>
  int(0)
}

**Comment by matyhtf** [comment]
请使用最新版本的swoole扩展
