### ISSUE TITLE
docker下的swoole压测大家的成绩怎么样？

### ISSUE THREAD

**Issue by wanjochan** [swoole/framework#117]
我在 docker下面做 nginx + php7 +swoole 的压测，只用简单的 echo rand();
出来的性能只有母体机的 1/5左右（docker已经用 -net=host），不知道大家的docker下面的dockerfile是怎么样的，压测的结果怎么样、母体机器硬件情况，在这个issues下面讨论下如何？

**Comment by xlight** [comment]
正常情况下 docker对rps的影响应该不到10%，性能损耗主要来自于proxy转发效率。
我个人压测也是符合上面的范围。

你使用 net=host应该影响会更小，
所以，你要看看是不是其他方面不一样导致的，比如 keep alive什么的。
