### ISSUE TITLE
给 swoole-framework 的建议

### ISSUE THREAD

**Issue by Moln** [swoole/framework#130]
建议：

1. 在PSR 各规范上做的很差，建议优化

    1.1. PSR1 不合格
    1.2. PSR2 不合格
    1.3. PSR0/4 不合格

2. 模块独立方面做的很差
3. 看里面竟然还有smarty，并不是所有人都喜欢这，建议运用 composer。

总体看出（个人意见）：

1. 作者对 composer  包依赖了解不太深入或不懂。
2. PSR 不太注重。
3. 这个框架架构，呃~~ 设计模式、独立性差
4. 总之这个框架当前版本是个大坑。

**Comment by aviggngyv** [comment]
看了最后一句，吓得我赶紧扔了
