### ISSUE TITLE
关于framework/libs/Swoole/Async/Pool.php 有两个问题想请教下

### ISSUE THREAD

**Issue by nick-william** [swoole/framework#133]
```php
 function remove($resource)
    {
        $rid = spl_object_hash($resource);
        if (!isset($this->resourcePool[$rid]))
        {
            return false;
        }

        //重建IdlePool
        $tmpPool = array();
        while(count($this->idlePool) > 0)
        {
            $_resource = $this->idlePool->dequeue();
            if (spl_object_hash($_resource) == $rid)
            {
                continue;
            }
            $tmpPool[] = $_resource;
        }
        //添加到空闲队列
        foreach($tmpPool as $_resource)
        {
            $this->idlePool->enqueue($_resource);
        }

        $this->resourceNum--;
        unset($rid);
        return true;
    }
```
对于上述的remove方法，有两处有点困惑，这里咨询下
问题一:      
 if (!isset($this->resourcePool[$rid]))
{
            return false;
}
在判断$this->resourcePool是否存在$resource的hash值，如果存在的话，是否需要直接unset($this->resourcePool[$rid]) ？？

问题二：
        $tmpPool = array();
        while(count($this->idlePool) > 0)
        {
            $_resource = $this->idlePool->dequeue();
            if (spl_object_hash($_resource) == $rid)
            {
                continue;
            }
            $tmpPool[] = $_resource;
        }
        //添加到空闲队列
        foreach($tmpPool as $_resource)
        {
            $this->idlePool->enqueue($_resource);
        }

此处将$this->idlePool队列中的$rid过滤掉；可是在doTask()方法中，$resource是直接从这个队列中获取的（$resource = $this->idlePool->dequeue(); ），这样的话不是能保证$this->idlePool中不存在$rid了吗，在这个$resource没有被销毁之前，其spl_object_hash值不是能保证唯一的吗？需要做这两次循环去过滤吗？

在看这个类的时候，有这两处不明，希望能点明一下

**Comment by matyhtf** [comment]
我不太明白你要表达的意思。

**Comment by nick-william** [comment]
不好意思，我重新描述下，都是关于remove方法的疑惑：
问题一：
if (!isset($this->resourcePool[$rid]))
 {
            return false;
}
这里判断isset的结果；不存在返回false；如果存在的话，是不是需要unset一下？

问题二：
//重建IdlePool这里；
现在使用的链接资源是从$this->idlePool->dequeue()获取的，这样的话，idlePool里面不是应该就不存在当前使用的资源了吗，为什么还要遍历一次过滤，然后在重新enqueue一下呢？

**Comment by matyhtf** [comment]
问题1，接下来的代码不是有unset吗
问题2，remove是连接关闭时调用的，肯定在idlePool中

**Comment by matyhtf** [comment]
第一个问题，代码确实存在BUG，已修复
