### ISSUE TITLE
memcached session过期时间

### ISSUE THREAD

**Issue by 9312xxxxxx** [swoole/framework#143]
`static $cache_lifetime = 0;`
`public function set($sessId, $session='')`
  `{`
      `     $key = self::$cache_prefix . $sessId;`
      `     $ret = $this->cache->set($key, $session, self::$cache_lifetime);`
     `      return $ret;`
 `   }`
开启memcached session处理，在设置session缓存时，过期时间是永不过期吗？

**Comment by 9312xxxxxx** [comment]
如果是永不过期，那么session的回收只能根据memcached的规则了，这样好吗？

**Comment by matyhtf** [comment]
在你的程序中调用 `Session::$cache_lifetime = 86400; ` 修改默认过期时间
