### ISSUE TITLE
__beforeAction和__afterAction的小建议

### ISSUE THREAD

**Issue by vs-ice** [swoole/framework#144]
libs\Swoole\Swoole.php 687行
`$this->callHook(self::HOOK_BEFORE_ACTION);`
`//magic method`
`if (method_exists($controller, '__beforeAction'))`
`{`
`    call_user_func(array($controller, '__beforeAction'), $mvc);`
`}`
 `//do action`
`$return = $controller->$method($param);`
`//magic method`
`if (method_exists($controller, '__afterAction'))`
`{`
`    call_user_func(array($controller, '__afterAction', $return));`
`}`
`//after action`
`$this->callHook(self::HOOK_AFTER_ACTION);`
1. 这里`call_user_func(array($controller, '__afterAction', $return));`array中应该是两项参数，里面有三项；
2. __beforeAction和__afterAction的方法非Public属性会出现异常；
3. __beforeAction和__afterAction如果产生输出，是否要先捕获，再根据before->action->after进行输出？

**Comment by matyhtf** [comment]
1, 已修复
2, 这个必须要public
3, 这2个回调函数内不捕获输出内容
