### ISSUE TITLE
flash websocket client连接案例里websocket服务的小问题

### ISSUE THREAD

**Issue by gushou** [swoole/framework#26]
运行exmaples里的websocket_server.php:
php websocket_server.php:

发现在firefox里能正常连接，而在ie8里调用连接会出现直接断线的情况。

调试跟踪发现，在libs/swoole/Request.php这个文件判断websocket有个大小写问题:
 function isWebSocket()
    {
        return isset($this->head['Upgrade']) && $this->head['Upgrade'] == 'websocket';
    }

在firefox里Upgrade头是全小写，而用flash websocket client是头字母大写--Websocket，故而连接失败。
该方法改成：
 function isWebSocket()
    {
        return isset($this->head['Upgrade']) && strtolower($this->head['Upgrade']) == 'websocket';
    }

目前运行正常。

**Comment by matyhtf** [comment]
已修复。
