### ISSUE TITLE
Header里的Cache控制

### ISSUE THREAD

**Issue by bebego** [swoole/framework#30]
系统：centos6.5 + swoole1.7.4 + swoole_framework。appserver模式
问题：验证码有时候点击会返回304的头，造成验证码不能正常显示，关闭expire_open后正常。

请求的相关头信息如下

一、首次请求，一切正常：
[2014-09-07 21:43:32]   INFO    new http request. fd=14
Swoole\Request Object
(
    [fd] => 14
    [id] => 
    [time] => 1410097412
    [remote_ip] => 192.168.137.1
    [get] => Array
        (
        )

    [post] => Array
        (
        )

    [file] => Array
        (
        )

    [cookie] => Array
        (
            [Hm_lvt_4967f2faa888a2e52742bebe7fcb5f7d] => 1408871467
            [PHPSESSID] => e0c70bf46468fcb79bf4c74b0e48fed8
            [cmstop_rememberusername] => cmstop
        )

    [session] => Array
        (
        )

    [server] => Array
        (
        )

    [attrs] => 
    [head] => Array
        (
            [Host] => 192.168.137.101:8888
            [User-Agent] => Mozilla/5.0 (Windows NT 6.1; WOW64; rv:28.0) Gecko/20100101 Firefox/28.0 FirePHP/0.7.4
            [Accept] => text/css,*/*;q=0.1
            [Accept-Language] => zh-cn,zh;q=0.8,en-us;q=0.5,en;q=0.3
            [Accept-Encoding] => gzip, deflate
            [Referer] => http://192.168.137.101:8888/admin/?app=system&controller=admin&action=login
            [Cookie] => Hm_lvt_4967f2faa888a2e52742bebe7fcb5f7d=1408871467; PHPSESSID=e0c70bf46468fcb79bf4c74b0e48fed8; cmstop_rememberusername=cmstop
            [x-insight] => activate
            [Connection] => keep-alive
            [If-Modified-Since] => Sun, 09-Jun-2013 02:26:34 CST
            [Cache-Control] => max-age=0
        )

    [body] => 
    [meta] => Array
        (
            [protocol] => HTTP/1.1
            [uri] => /admin/css/admin.css
            [method] => GET
            [path] => /admin/css/admin.css
        )

    [finish] => 
    [ext_name] => 
    [status] => 
)
Array
(
    [0] => admin
    [1] => css
    [2] => admin.css
)
Swoole\Response Object
(
    [http_protocol] => HTTP/1.1
    [http_status] => 304
    [head] => Array
        (
            [0] => HTTP/1.1 304 Not Modified
            [Date] => Sun, 07 Sep 2014 13:43:32 GMT
            [KeepAlive] => on
            [Connection] => keep-alive
        )

    [cookie] => 
    [body] => 
)
[2014-09-07 21:43:32]   INFO    client[#15@0] connect
[2014-09-07 21:43:32]   INFO    client[#16@0] connect
[2014-09-07 21:43:32]   INFO    client[#17@0] connect
[2014-09-07 21:43:32]   INFO    client[#18@0] connect
[2014-09-07 21:43:32]   INFO    new http request. fd=15
Swoole\Request Object
(
    [fd] => 15
    [id] => 
    [time] => 1410097412
    [remote_ip] => 192.168.137.1
    [get] => Array
        (
        )

    [post] => Array
        (
        )

    [file] => Array
        (
        )

    [cookie] => Array
        (
            [Hm_lvt_4967f2faa888a2e52742bebe7fcb5f7d] => 1408871467
            [PHPSESSID] => e0c70bf46468fcb79bf4c74b0e48fed8
            [cmstop_rememberusername] => cmstop
        )

    [session] => Array
        (
        )

    [server] => Array
        (
        )

    [attrs] => 
    [head] => Array
        (
            [Host] => 192.168.137.101:8888
            [User-Agent] => Mozilla/5.0 (Windows NT 6.1; WOW64; rv:28.0) Gecko/20100101 Firefox/28.0 FirePHP/0.7.4
            [Accept] => text/css,*/*;q=0.1
            [Accept-Language] => zh-cn,zh;q=0.8,en-us;q=0.5,en;q=0.3
            [Accept-Encoding] => gzip, deflate
            [Referer] => http://192.168.137.101:8888/admin/?app=system&controller=admin&action=login
            [Cookie] => Hm_lvt_4967f2faa888a2e52742bebe7fcb5f7d=1408871467; PHPSESSID=e0c70bf46468fcb79bf4c74b0e48fed8; cmstop_rememberusername=cmstop
            [x-insight] => activate
            [Connection] => keep-alive
            [If-Modified-Since] => Sun, 07-Apr-2013 09:32:11 CST
            [Cache-Control] => max-age=0
        )

    [body] => 
    [meta] => Array
        (
            [protocol] => HTTP/1.1
            [uri] => /img/js/lib/validator/style.css
            [method] => GET
            [path] => /img/js/lib/validator/style.css
        )

    [finish] => 
    [ext_name] => 
    [status] => 
)
Array
(
    [0] => img
    [1] => js
    [2] => lib
    [3] => validator
    [4] => style.css
)
Swoole\Response Object
(
    [http_protocol] => HTTP/1.1
    [http_status] => 304
    [head] => Array
        (
            [0] => HTTP/1.1 304 Not Modified
            [Date] => Sun, 07 Sep 2014 13:43:32 GMT
            [KeepAlive] => on
            [Connection] => keep-alive
        )

    [cookie] => 
    [body] => 
)
[2014-09-07 21:43:32]   INFO    new http request. fd=16
Swoole\Request Object
(
    [fd] => 16
    [id] => 
    [time] => 1410097412
    [remote_ip] => 192.168.137.1
    [get] => Array
        (
        )

    [post] => Array
        (
        )

    [file] => Array
        (
        )

    [cookie] => Array
        (
            [Hm_lvt_4967f2faa888a2e52742bebe7fcb5f7d] => 1408871467
            [PHPSESSID] => e0c70bf46468fcb79bf4c74b0e48fed8
            [cmstop_rememberusername] => cmstop
        )

    [session] => Array
        (
        )

    [server] => Array
        (
        )

    [attrs] => 
    [head] => Array
        (
            [Host] => 192.168.137.101:8888
            [User-Agent] => Mozilla/5.0 (Windows NT 6.1; WOW64; rv:28.0) Gecko/20100101 Firefox/28.0 FirePHP/0.7.4
            [Accept] => */*
            [Accept-Language] => zh-cn,zh;q=0.8,en-us;q=0.5,en;q=0.3
            [Accept-Encoding] => gzip, deflate
            [Referer] => http://192.168.137.101:8888/admin/?app=system&controller=admin&action=login
            [Cookie] => Hm_lvt_4967f2faa888a2e52742bebe7fcb5f7d=1408871467; PHPSESSID=e0c70bf46468fcb79bf4c74b0e48fed8; cmstop_rememberusername=cmstop
            [x-insight] => activate
            [Connection] => keep-alive
            [If-Modified-Since] => Sat, 02-Aug-2014 14:24:06 CST
            [Cache-Control] => max-age=0
        )

    [body] => 
    [meta] => Array
        (
            [protocol] => HTTP/1.1
            [uri] => /img/js/lib/jquery.js
            [method] => GET
            [path] => /img/js/lib/jquery.js
        )

    [finish] => 
    [ext_name] => 
    [status] => 
)
Array
(
    [0] => img
    [1] => js
    [2] => lib
    [3] => jquery.js
)
Swoole\Response Object
(
    [http_protocol] => HTTP/1.1
    [http_status] => 304
    [head] => Array
        (
            [0] => HTTP/1.1 304 Not Modified
            [Date] => Sun, 07 Sep 2014 13:43:32 GMT
            [KeepAlive] => on
            [Connection] => keep-alive
        )

    [cookie] => 
    [body] => 
)
[2014-09-07 21:43:32]   INFO    client[#19@0] connect
[2014-09-07 21:43:32]   INFO    new http request. fd=17
Swoole\Request Object
(
    [fd] => 17
    [id] => 
    [time] => 1410097412
    [remote_ip] => 192.168.137.1
    [get] => Array
        (
        )

    [post] => Array
        (
        )

    [file] => Array
        (
        )

    [cookie] => Array
        (
            [Hm_lvt_4967f2faa888a2e52742bebe7fcb5f7d] => 1408871467
            [PHPSESSID] => e0c70bf46468fcb79bf4c74b0e48fed8
            [cmstop_rememberusername] => cmstop
        )

    [session] => Array
        (
        )

    [server] => Array
        (
        )

    [attrs] => 
    [head] => Array
        (
            [Host] => 192.168.137.101:8888
            [User-Agent] => Mozilla/5.0 (Windows NT 6.1; WOW64; rv:28.0) Gecko/20100101 Firefox/28.0 FirePHP/0.7.4
            [Accept] => */*
            [Accept-Language] => zh-cn,zh;q=0.8,en-us;q=0.5,en;q=0.3
            [Accept-Encoding] => gzip, deflate
            [Referer] => http://192.168.137.101:8888/admin/?app=system&controller=admin&action=login
            [Cookie] => Hm_lvt_4967f2faa888a2e52742bebe7fcb5f7d=1408871467; PHPSESSID=e0c70bf46468fcb79bf4c74b0e48fed8; cmstop_rememberusername=cmstop
            [x-insight] => activate
            [Connection] => keep-alive
            [If-Modified-Since] => Sun, 14-Jul-2013 21:03:37 CST
            [Cache-Control] => max-age=0
        )

    [body] => 
    [meta] => Array
        (
            [protocol] => HTTP/1.1
            [uri] => /img/js/config.js
            [method] => GET
            [path] => /img/js/config.js
        )

    [finish] => 
    [ext_name] => 
    [status] => 
)
Array
(
    [0] => img
    [1] => js
    [2] => config.js
)
Swoole\Response Object
(
    [http_protocol] => HTTP/1.1
    [http_status] => 304
    [head] => Array
        (
            [0] => HTTP/1.1 304 Not Modified
            [Date] => Sun, 07 Sep 2014 13:43:32 GMT
            [KeepAlive] => on
            [Connection] => keep-alive
        )

    [cookie] => 
    [body] => 
)
[2014-09-07 21:43:32]   INFO    new http request. fd=18
Swoole\Request Object
(
    [fd] => 18
    [id] => 
    [time] => 1410097412
    [remote_ip] => 192.168.137.1
    [get] => Array
        (
        )

    [post] => Array
        (
        )

    [file] => Array
        (
        )

    [cookie] => Array
        (
            [Hm_lvt_4967f2faa888a2e52742bebe7fcb5f7d] => 1408871467
            [PHPSESSID] => e0c70bf46468fcb79bf4c74b0e48fed8
            [cmstop_rememberusername] => cmstop
        )

    [session] => Array
        (
        )

    [server] => Array
        (
        )

    [attrs] => 
    [head] => Array
        (
            [Host] => 192.168.137.101:8888
            [User-Agent] => Mozilla/5.0 (Windows NT 6.1; WOW64; rv:28.0) Gecko/20100101 Firefox/28.0 FirePHP/0.7.4
            [Accept] => */*
            [Accept-Language] => zh-cn,zh;q=0.8,en-us;q=0.5,en;q=0.3
            [Accept-Encoding] => gzip, deflate
            [Referer] => http://192.168.137.101:8888/admin/?app=system&controller=admin&action=login
            [Cookie] => Hm_lvt_4967f2faa888a2e52742bebe7fcb5f7d=1408871467; PHPSESSID=e0c70bf46468fcb79bf4c74b0e48fed8; cmstop_rememberusername=cmstop
            [x-insight] => activate
            [Connection] => keep-alive
            [If-Modified-Since] => Tue, 23-Jul-2013 19:25:24 CST
            [Cache-Control] => max-age=0
        )

    [body] => 
    [meta] => Array
        (
            [protocol] => HTTP/1.1
            [uri] => /img/js/cmstop.js
            [method] => GET
            [path] => /img/js/cmstop.js
        )

    [finish] => 
    [ext_name] => 
    [status] => 
)
Array
(
    [0] => img
    [1] => js
    [2] => cmstop.js
)
Swoole\Response Object
(
    [http_protocol] => HTTP/1.1
    [http_status] => 304
    [head] => Array
        (
            [0] => HTTP/1.1 304 Not Modified
            [Date] => Sun, 07 Sep 2014 13:43:32 GMT
            [KeepAlive] => on
            [Connection] => keep-alive
        )

    [cookie] => 
    [body] => 
)
[2014-09-07 21:43:32]   INFO    new http request. fd=19
Swoole\Request Object
(
    [fd] => 19
    [id] => 
    [time] => 1410097412
    [remote_ip] => 192.168.137.1
    [get] => Array
        (
        )

    [post] => Array
        (
        )

    [file] => Array
        (
        )

    [cookie] => Array
        (
            [Hm_lvt_4967f2faa888a2e52742bebe7fcb5f7d] => 1408871467
            [PHPSESSID] => e0c70bf46468fcb79bf4c74b0e48fed8
            [cmstop_rememberusername] => cmstop
        )

    [session] => Array
        (
        )

    [server] => Array
        (
        )

    [attrs] => 
    [head] => Array
        (
            [Host] => 192.168.137.101:8888
            [User-Agent] => Mozilla/5.0 (Windows NT 6.1; WOW64; rv:28.0) Gecko/20100101 Firefox/28.0 FirePHP/0.7.4
            [Accept] => */*
            [Accept-Language] => zh-cn,zh;q=0.8,en-us;q=0.5,en;q=0.3
            [Accept-Encoding] => gzip, deflate
            [Referer] => http://192.168.137.101:8888/admin/?app=system&controller=admin&action=login
            [Cookie] => Hm_lvt_4967f2faa888a2e52742bebe7fcb5f7d=1408871467; PHPSESSID=e0c70bf46468fcb79bf4c74b0e48fed8; cmstop_rememberusername=cmstop
            [x-insight] => activate
            [Connection] => keep-alive
            [If-Modified-Since] => Fri, 02-Mar-2012 16:20:46 CST
            [Cache-Control] => max-age=0
        )

    [body] => 
    [meta] => Array
        (
            [protocol] => HTTP/1.1
            [uri] => /img/js/lib/jquery.cookie.js
            [method] => GET
            [path] => /img/js/lib/jquery.cookie.js
        )

    [finish] => 
    [ext_name] => 
    [status] => 
)
Array
(
    [0] => img
    [1] => js
    [2] => lib
    [3] => jquery.cookie.js
)
Swoole\Response Object
(
    [http_protocol] => HTTP/1.1
    [http_status] => 304
    [head] => Array
        (
            [0] => HTTP/1.1 304 Not Modified
            [Date] => Sun, 07 Sep 2014 13:43:32 GMT
            [KeepAlive] => on
            [Connection] => keep-alive
        )

    [cookie] => 
    [body] => 
)
[2014-09-07 21:43:32]   INFO    new http request. fd=14
Swoole\Request Object
(
    [fd] => 14
    [id] => 
    [time] => 1410097412
    [remote_ip] => 192.168.137.1
    [get] => Array
        (
        )

    [post] => Array
        (
        )

    [file] => Array
        (
        )

    [cookie] => Array
        (
            [Hm_lvt_4967f2faa888a2e52742bebe7fcb5f7d] => 1408871467
            [PHPSESSID] => e0c70bf46468fcb79bf4c74b0e48fed8
            [cmstop_rememberusername] => cmstop
        )

    [session] => Array
        (
        )

    [server] => Array
        (
        )

    [attrs] => 
    [head] => Array
        (
            [Host] => 192.168.137.101:8888
            [User-Agent] => Mozilla/5.0 (Windows NT 6.1; WOW64; rv:28.0) Gecko/20100101 Firefox/28.0 FirePHP/0.7.4
            [Accept] => text/css,*/*;q=0.1
            [Accept-Language] => zh-cn,zh;q=0.8,en-us;q=0.5,en;q=0.3
            [Accept-Encoding] => gzip, deflate
            [Referer] => http://192.168.137.101:8888/admin/?app=system&controller=admin&action=login
            [Cookie] => Hm_lvt_4967f2faa888a2e52742bebe7fcb5f7d=1408871467; PHPSESSID=e0c70bf46468fcb79bf4c74b0e48fed8; cmstop_rememberusername=cmstop
            [x-insight] => activate
            [Connection] => keep-alive
            [If-Modified-Since] => Sun, 09-Jun-2013 02:26:34 CST
            [Cache-Control] => max-age=0
        )

    [body] => GET /admin/?app=system&controller=seccode&action=image HTTP/1.1
Host: 192.168.137.101:8888
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:28.0) Gecko/20100101 Firefox/28.0 FirePHP/0.7.4
Accept: image/png,image/*;q=0.8,*/*;q=0.5
Accept-Language: zh-cn,zh;q=0.8,en-us;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate
Referer: http://192.168.137.101:8888/admin/?app=system&controller=admin&action=login
Cookie: Hm_lvt_4967f2faa888a2e52742bebe7fcb5f7d=1408871467; PHPSESSID=e0c70bf46468fcb79bf4c74b0e48fed8; cmstop_rememberusername=cmstop
x-insight: activate
Connection: keep-alive
Cache-Control: max-age=0

    [meta] => Array
        (
            [protocol] => HTTP/1.1
            [uri] => /admin/css/admin.css
            [method] => GET
            [path] => /admin/css/admin.css
        )

    [finish] => 
    [ext_name] => css
    [status] => 
)
Array
(
    [0] => admin
    [1] => css
    [2] => admin.css
)
Swoole\Response Object
(
    [http_protocol] => HTTP/1.1
    [http_status] => 304
    [head] => Array
        (
            [0] => HTTP/1.1 304 Not Modified
            [Date] => Sun, 07 Sep 2014 13:43:32 GMT
            [KeepAlive] => on
            [Connection] => keep-alive
        )

    [cookie] => 
    [body] => 
)
[2014-09-07 21:43:33]   INFO    new http request. fd=14
Swoole\Request Object
(
    [fd] => 14
    [id] => 
    [time] => 1410097413
    [remote_ip] => 192.168.137.1
    [get] => Array
        (
        )

    [post] => Array
        (
        )

    [file] => Array
        (
        )

    [cookie] => Array
        (
            [Hm_lvt_4967f2faa888a2e52742bebe7fcb5f7d] => 1408871467
            [PHPSESSID] => e0c70bf46468fcb79bf4c74b0e48fed8
            [cmstop_rememberusername] => cmstop
        )

    [session] => Array
        (
        )

    [server] => Array
        (
        )

    [attrs] => 
    [head] => Array
        (
            [Host] => 192.168.137.101:8888
            [User-Agent] => Mozilla/5.0 (Windows NT 6.1; WOW64; rv:28.0) Gecko/20100101 Firefox/28.0 FirePHP/0.7.4
            [Accept] => text/css,*/*;q=0.1
            [Accept-Language] => zh-cn,zh;q=0.8,en-us;q=0.5,en;q=0.3
            [Accept-Encoding] => gzip, deflate
            [Referer] => http://192.168.137.101:8888/admin/?app=system&controller=admin&action=login
            [Cookie] => Hm_lvt_4967f2faa888a2e52742bebe7fcb5f7d=1408871467; PHPSESSID=e0c70bf46468fcb79bf4c74b0e48fed8; cmstop_rememberusername=cmstop
            [x-insight] => activate
            [Connection] => keep-alive
            [If-Modified-Since] => Sun, 09-Jun-2013 02:26:34 CST
            [Cache-Control] => max-age=0
        )

    [body] => GET /admin/?app=system&controller=seccode&action=image HTTP/1.1
Host: 192.168.137.101:8888
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:28.0) Gecko/20100101 Firefox/28.0 FirePHP/0.7.4
Accept: image/png,image/*;q=0.8,*/*;q=0.5
Accept-Language: zh-cn,zh;q=0.8,en-us;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate
Referer: http://192.168.137.101:8888/admin/?app=system&controller=admin&action=login
Cookie: Hm_lvt_4967f2faa888a2e52742bebe7fcb5f7d=1408871467; PHPSESSID=e0c70bf46468fcb79bf4c74b0e48fed8; cmstop_rememberusername=cmstop
x-insight: activate
Connection: keep-alive
Cache-Control: max-age=0

GET /admin/css/images/bg_login.jpg HTTP/1.1
Host: 192.168.137.101:8888
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:28.0) Gecko/20100101 Firefox/28.0 FirePHP/0.7.4
Accept: image/png,image/*;q=0.8,*/*;q=0.5
Accept-Language: zh-cn,zh;q=0.8,en-us;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate
Referer: http://192.168.137.101:8888/admin/?app=system&controller=admin&action=login
Cookie: Hm_lvt_4967f2faa888a2e52742bebe7fcb5f7d=1408871467; PHPSESSID=e0c70bf46468fcb79bf4c74b0e48fed8; cmstop_rememberusername=cmstop
x-insight: activate
Connection: keep-alive
If-Modified-Since: Thu, 20-Jun-2013 22:31:47 CST
Cache-Control: max-age=0

    [meta] => Array
        (
            [protocol] => HTTP/1.1
            [uri] => /admin/css/admin.css
            [method] => GET
            [path] => /admin/css/admin.css
        )

    [finish] => 
    [ext_name] => css
    [status] => 
)
Array
(
    [0] => admin
    [1] => css
    [2] => admin.css
)
Swoole\Response Object
(
    [http_protocol] => HTTP/1.1
    [http_status] => 304
    [head] => Array
        (
            [0] => HTTP/1.1 304 Not Modified
            [Date] => Sun, 07 Sep 2014 13:43:33 GMT
            [KeepAlive] => on
            [Connection] => keep-alive
        )

    [cookie] => 
    [body] => 
)
[2014-09-07 21:43:33]   INFO    new http request. fd=15
Swoole\Request Object
(
    [fd] => 15
    [id] => 
    [time] => 1410097413
    [remote_ip] => 192.168.137.1
    [get] => Array
        (
        )

    [post] => Array
        (
        )

    [file] => Array
        (
        )

    [cookie] => Array
        (
            [Hm_lvt_4967f2faa888a2e52742bebe7fcb5f7d] => 1408871467
            [PHPSESSID] => e0c70bf46468fcb79bf4c74b0e48fed8
            [cmstop_rememberusername] => cmstop
        )

    [session] => Array
        (
        )

    [server] => Array
        (
        )

    [attrs] => 
    [head] => Array
        (
            [Host] => 192.168.137.101:8888
            [User-Agent] => Mozilla/5.0 (Windows NT 6.1; WOW64; rv:28.0) Gecko/20100101 Firefox/28.0 FirePHP/0.7.4
            [Accept] => text/css,*/*;q=0.1
            [Accept-Language] => zh-cn,zh;q=0.8,en-us;q=0.5,en;q=0.3
            [Accept-Encoding] => gzip, deflate
            [Referer] => http://192.168.137.101:8888/admin/?app=system&controller=admin&action=login
            [Cookie] => Hm_lvt_4967f2faa888a2e52742bebe7fcb5f7d=1408871467; PHPSESSID=e0c70bf46468fcb79bf4c74b0e48fed8; cmstop_rememberusername=cmstop
            [x-insight] => activate
            [Connection] => keep-alive
            [If-Modified-Since] => Sun, 07-Apr-2013 09:32:11 CST
            [Cache-Control] => max-age=0
        )

    [body] => GET /admin/css/images/bg.gif HTTP/1.1
Host: 192.168.137.101:8888
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:28.0) Gecko/20100101 Firefox/28.0 FirePHP/0.7.4
Accept: image/png,image/*;q=0.8,*/*;q=0.5
Accept-Language: zh-cn,zh;q=0.8,en-us;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate
Referer: http://192.168.137.101:8888/admin/?app=system&controller=admin&action=login
Cookie: Hm_lvt_4967f2faa888a2e52742bebe7fcb5f7d=1408871467; PHPSESSID=e0c70bf46468fcb79bf4c74b0e48fed8; cmstop_rememberusername=cmstop
x-insight: activate
Connection: keep-alive
If-Modified-Since: Sun, 07-Apr-2013 14:32:42 CST
Cache-Control: max-age=0

    [meta] => Array
        (
            [protocol] => HTTP/1.1
            [uri] => /img/js/lib/validator/style.css
            [method] => GET
            [path] => /img/js/lib/validator/style.css
        )

    [finish] => 
    [ext_name] => css
    [status] => 
)
Array
(
    [0] => img
    [1] => js
    [2] => lib
    [3] => validator
    [4] => style.css
)
Swoole\Response Object
(
    [http_protocol] => HTTP/1.1
    [http_status] => 304
    [head] => Array
        (
            [0] => HTTP/1.1 304 Not Modified
            [Date] => Sun, 07 Sep 2014 13:43:33 GMT
            [KeepAlive] => on
            [Connection] => keep-alive
        )

    [cookie] => 
    [body] => 
)
[2014-09-07 21:45:28]   INFO    client[#14@0] close
[2014-09-07 21:45:29]   INFO    client[#15@0] close
[2014-09-07 21:45:29]   INFO    client[#18@0] close
[2014-09-07 21:45:29]   INFO    client[#17@0] close
[2014-09-07 21:45:29]   INFO    client[#16@0] close
[2014-09-07 21:45:29]   INFO    client[#19@0] close

二、单独刷新验证码
[2014-09-07 21:48:09]   INFO    new http request. fd=14
Swoole\Request Object
(
    [fd] => 14
    [id] => 
    [time] => 1410097689
    [remote_ip] => 192.168.137.1
    [get] => Array
        (
        )

    [post] => Array
        (
        )

    [file] => Array
        (
        )

    [cookie] => Array
        (
            [Hm_lvt_4967f2faa888a2e52742bebe7fcb5f7d] => 1408871467
            [PHPSESSID] => e0c70bf46468fcb79bf4c74b0e48fed8
            [cmstop_rememberusername] => cmstop
        )

    [session] => Array
        (
        )

    [server] => Array
        (
        )

    [attrs] => 
    [head] => Array
        (
            [Host] => 192.168.137.101:8888
            [User-Agent] => Mozilla/5.0 (Windows NT 6.1; WOW64; rv:28.0) Gecko/20100101 Firefox/28.0 FirePHP/0.7.4
            [Accept] => text/css,*/*;q=0.1
            [Accept-Language] => zh-cn,zh;q=0.8,en-us;q=0.5,en;q=0.3
            [Accept-Encoding] => gzip, deflate
            [Referer] => http://192.168.137.101:8888/admin/?app=system&controller=admin&action=login
            [Cookie] => Hm_lvt_4967f2faa888a2e52742bebe7fcb5f7d=1408871467; PHPSESSID=e0c70bf46468fcb79bf4c74b0e48fed8; cmstop_rememberusername=cmstop
            [x-insight] => activate
            [Connection] => keep-alive
            [If-Modified-Since] => Sun, 09-Jun-2013 02:26:34 CST
            [Cache-Control] => max-age=0
        )

    [body] => GET /admin/?app=system&controller=seccode&action=image HTTP/1.1
Host: 192.168.137.101:8888
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:28.0) Gecko/20100101 Firefox/28.0 FirePHP/0.7.4
Accept: image/png,image/*;q=0.8,*/*;q=0.5
Accept-Language: zh-cn,zh;q=0.8,en-us;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate
Referer: http://192.168.137.101:8888/admin/?app=system&controller=admin&action=login
Cookie: Hm_lvt_4967f2faa888a2e52742bebe7fcb5f7d=1408871467; PHPSESSID=e0c70bf46468fcb79bf4c74b0e48fed8; cmstop_rememberusername=cmstop
x-insight: activate
Connection: keep-alive
Cache-Control: max-age=0

GET /admin/css/images/bg_login.jpg HTTP/1.1
Host: 192.168.137.101:8888
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:28.0) Gecko/20100101 Firefox/28.0 FirePHP/0.7.4
Accept: image/png,image/*;q=0.8,*/*;q=0.5
Accept-Language: zh-cn,zh;q=0.8,en-us;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate
Referer: http://192.168.137.101:8888/admin/?app=system&controller=admin&action=login
Cookie: Hm_lvt_4967f2faa888a2e52742bebe7fcb5f7d=1408871467; PHPSESSID=e0c70bf46468fcb79bf4c74b0e48fed8; cmstop_rememberusername=cmstop
x-insight: activate
Connection: keep-alive
If-Modified-Since: Thu, 20-Jun-2013 22:31:47 CST
Cache-Control: max-age=0

GET /admin/?app=system&controller=seccode&action=image&id=2.2640411798197704 HTTP/1.1
Host: 192.168.137.101:8888
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:28.0) Gecko/20100101 Firefox/28.0 FirePHP/0.7.4
Accept: image/png,image/*;q=0.8,*/*;q=0.5
Accept-Language: zh-cn,zh;q=0.8,en-us;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate
Referer: http://192.168.137.101:8888/admin/?app=system&controller=admin&action=login
Cookie: Hm_lvt_4967f2faa888a2e52742bebe7fcb5f7d=1408871467; PHPSESSID=e0c70bf46468fcb79bf4c74b0e48fed8; cmstop_rememberusername=cmstop
x-insight: activate
Connection: keep-alive

    [meta] => Array
        (
            [protocol] => HTTP/1.1
            [uri] => /admin/css/admin.css
            [method] => GET
            [path] => /admin/css/admin.css
        )

    [finish] => 
    [ext_name] => css
    [status] => 
)
Array
(
    [0] => admin
    [1] => css
    [2] => admin.css
)
Swoole\Response Object
(
    [http_protocol] => HTTP/1.1
    [http_status] => 304
    [head] => Array
        (
            [0] => HTTP/1.1 304 Not Modified
            [Date] => Sun, 07 Sep 2014 13:48:09 GMT
            [KeepAlive] => on
            [Connection] => keep-alive
        )

    [cookie] => 
    [body] => 
)

**Comment by xxiyj** [comment]
升级下swoole版本，

**Comment by matyhtf** [comment]
关闭 expire_open 吧

**Comment by niboge** [comment]
每次请求都要刷一遍css js 。关闭expire_open也不太好啊！
