### ISSUE TITLE
/usr/include/php5/ext/mysqli/php_mysqli_structs.h:63:23: fatal error: my_global.h: No such file or directory

### ISSUE THREAD

**Issue by yiliaofan** [swoole/framework#38]
fan@xx0:~/www/server/php/swoole-src-swoole-1.7.9-stable$ ./configure  --with-php-config=/usr/bin/php-config --enable-swoole-debug --enable-sockets --enable-ringbuffer --enable-async-mysql --enable-openssl --with-swoole --enable-swoole --enable-debug

fan@xx0:~/www/server/php/swoole-src-swoole-1.7.9-stable$ make
/bin/bash /home/fan/www/server/php/swoole-src-swoole-1.7.9-stable/libtool --mode=compile cc  -I. -I/home/fan/www/server/php/swoole-src-swoole-1.7.9-stable -DPHP_ATOM_INC -I/home/fan/www/server/php/swoole-src-swoole-1.7.9-stable/include -I/home/fan/www/server/php/swoole-src-swoole-1.7.9-stable/main -I/home/fan/www/server/php/swoole-src-swoole-1.7.9-stable -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -I/include  -DHAVE_CONFIG_H  -Wall -pthread -g -O2   -c /home/fan/www/server/php/swoole-src-swoole-1.7.9-stable/swoole.c -o swoole.lo 
libtool: compile:  cc -I. -I/home/fan/www/server/php/swoole-src-swoole-1.7.9-stable -DPHP_ATOM_INC -I/home/fan/www/server/php/swoole-src-swoole-1.7.9-stable/include -I/home/fan/www/server/php/swoole-src-swoole-1.7.9-stable/main -I/home/fan/www/server/php/swoole-src-swoole-1.7.9-stable -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -I/include -DHAVE_CONFIG_H -Wall -pthread -g -O2 -c /home/fan/www/server/php/swoole-src-swoole-1.7.9-stable/swoole.c  -fPIC -DPIC -o .libs/swoole.o
In file included from /home/fan/www/server/php/swoole-src-swoole-1.7.9-stable/swoole.c:280:0:
/usr/include/php5/ext/mysqli/php_mysqli_structs.h:63:23: fatal error: my_global.h: No such file or directory
 #include <my_global.h>
                       ^
compilation terminated.
make: *** [swoole.lo] 错误 1

官方的说明已试过，如下：
缺少mysql头文件

php_mysqli_structs.h:64:23: fatal error: my_global.h: No such file or directory 没有找到mysqlclient的头文件，需要安装mysqlclient-dev

sudo apt-get install libmysqlclient-dev 还是不行？

有没有通用的解决方案？ 谢谢了

**Comment by betashepherd** [comment]
发下 php  -m  结果。   另外编译的时候需要指定参数   with-mysqli

yiliaofan <notifications@github.com>编写：

**Comment by yiliaofan** [comment]
an@fan-ThinkPad-Edge-E440:~/www/server/php/swoole-src-swoole-1.7.9-stable$ php -m
[PHP Modules]
bcmath
bz2
Core
ctype
curl
date
dom
ereg
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
libxml
mbstring
mcrypt
mysql
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
sqlite3
standard
sysvsem
tokenizer
wddx
xml
xmlreader
xmlrpc
xmlwriter
zip
zlib

[Zend Modules]

**Comment by matyhtf** [comment]
缺少一些头文件，最好是自己下载php源码，编译安装。

**Comment by Youngyezi** [comment]
能分享下你的解决方法么，我现在也遇到了这么问题

**Comment by zhj-mid** [comment]
php-config指定路径应该是什么啊
