### ISSUE TITLE
使用Database Driver 是 PDO，有错误提示。

### ISSUE THREAD

**Issue by xxluan** [swoole/framework#43]
使用Database Driver 是 PDO，有以下提示：

Strict Standards: Declaration of Swoole\Database\PdoDB::quote() should be compatible with PDO::quote($string, $paramtype = NULL) in /data0/htdocs/swoole_web/libs/Swoole/Database/PdoDB.php on line 66

**Comment by xxluan** [comment]
pdo屏蔽掉这个方法就行了。

**Comment by xxluan** [comment]
这样是不是防止不了sql注入？

**Comment by matyhtf** [comment]
修复一下。对，需要使用quote来处理字符串。
