### ISSUE TITLE
使用pdo连接mysql，配置长连接为false，超过一定时间后访问，会出现MySQL server has gone away

### ISSUE THREAD

**Issue by xxluan** [swoole/framework#47]
![image](https://cloud.githubusercontent.com/assets/1575668/6933290/9c0d99ce-d857-11e4-95c7-974d07a887e2.png)

以上是配置参数，请问如何能避免出现这个问题？

**Comment by xxluan** [comment]
另外 libs\swoole\database.php的 check_status 检查连接状态，如果连接断开，则重新连接。
这个方法不起作用吗？需要在业务层的代码调用吗？还是已经在框架代码里边调用了？

**Comment by matyhtf** [comment]
PDO目前不支持断线重连，需要自行实现。可以使用MySQLi作为数据库类型

**Comment by xxluan** [comment]
使用MySQLi，需要在每个业务代码执行完后，再执行db close吗？

**Comment by matyhtf** [comment]
不需要执行db close.
