### ISSUE TITLE
启用gzip_open=1，访问页面的响应头还是没有压缩

### ISSUE THREAD

**Issue by xxluan** [swoole/framework#48]
![image](https://cloud.githubusercontent.com/assets/1575668/6956932/6541b896-d927-11e4-8c6d-ff86a706f30d.png)

另外，请问nginx的gzip压缩 和 framework的框架压缩，哪个比较好？

**Comment by xxluan** [comment]
我现在用的是1.7.13，应该没有gzip支持吧？
另外，请问nginx的gzip压缩 和 framework的框架压缩，哪个比较好？

**Comment by xxiyj** [comment]
开启gzip后， 网页在微信中打开，部分手机会造成乱码

**Comment by matyhtf** [comment]
建议Nginx的压缩。
