### ISSUE TITLE
如何热部署，代码更新后即刻生效？

### ISSUE THREAD

**Issue by xxluan** [swoole/framework#49]
热部署，代码更新后即刻生效。依赖runkit扩展。
是不是安装了runkit扩展，就可以了？
没看懂runkit在说什么。。
跪求中文步骤。。

**Comment by xxluan** [comment]
runkit扩展编译不过去。。。在那边发帖问作者了

**Comment by xxiyj** [comment]
我也编译没有通过， php5.6

**Comment by xxluan** [comment]
我的是5.6.2

**Comment by xxiyj** [comment]
https://github.com/php/pecl-php-runkit

需要在这个下载最新runkit扩展
需要git下载最新的： （否则不行）
git clone https://github.com/php/pecl-php-runkit.git

**Comment by xxiyj** [comment]
然后需要在 swoole.ini 中打开 auto_reload = 1

**Comment by xxluan** [comment]
更新代码后，等很久才会自动更新，你有遇到吗？

**Comment by xxiyj** [comment]
你是用的我这个版本吗， 我上传了 再访问就马上更新了

**Comment by wanjochan** [comment]
简单总结一下：

一、runkit 扩展一直没能兼容php7（是不是停止维护了？）
二、除了runkit还有没有其它热部署方案？
三、因为热部署方案还没通过，所以用 swoole 跑 FastCGI (参见swoole的 https://github.com/swoole/framework/blob/master/libs/Swoole/Protocol/FastCGI.php) 时代码不能即时生效， 这样在实用性上暂时还没办法取代 php-fpm 。当然都是在说PHP7。。。

PHP-FPM始终是要淘汰掉的，Swoole要一统江湖至少在 这个层面上能直接取而代之，成为 nginx的最佳拍档。。。

**Comment by wanjochan** [comment]
runkit 好像真的放弃对php7做更新。。。
https://github.com/zenovich/runkit/issues/87

**Comment by wanjochan** [comment]
求人不如求己，准备开干用 swoole做堡垒
动态＝>飞后端 php-fpm
其它=>飞本地
主要是需要取代nginx可以做快速的部署

**Comment by xxiyj** [comment]
GitHook Git 钩子程序，Github/Bitbucket repo 在某个分支发生 push 行为的时候，自动触发一段脚本重启swoole server
https://github.com/wenjun1055/githook

**Comment by wanjochan** [comment]
@xxiyj  重启server并不是热部署。。。
