### ISSUE TITLE
框架底层报错：PHP Warning:  file_put_contents(): Filename cannot be empty in 

### ISSUE THREAD

**Issue by winerQin** [swoole/framework#76]
PHP Warning:  file_put_contents(): Filename cannot be empty in /Users/winerQin/workspace/myself/osc_swoole_core/vendor/matyhtf/swoole_framework/libs/Swoole/Network/Server.php on line 144

```
function onMasterStart($serv)
    {
        global $argv;
        Swoole\Console::setProcessName('php ' . $argv[0] . ': master -host=' . $this->host . ' -port=' . $this->port);
        
        if (!empty($this->runtimeSetting['pid_file']))
        {
            file_put_contents(self::$pidFile, $serv->master_pid);
        }
    }
```

144行代码为：
```
 file_put_contents(self::$pidFile, $serv->master_pid);
```

可得知$serv->master_pid没有值。我不知道怎么打印。所以，不知道是否打印出来。

**Comment by lscgzwd** [comment]
这个错误是，你没有设置pid_file，需要先调用：
//设置PID文件的存储路径
Swoole\Network\Server::setPidFile(__DIR__ . '/app_server.pid');
