### ISSUE TITLE
core error: Swoole: Swoole::$app_path and WEBPATH empty.

### ISSUE THREAD

**Issue by viile** [swoole/framework#81]
[root@localhost framework]# php server.php 
core error: Swoole: Swoole::$app_path and WEBPATH empty.
----------------------------------------------------------------------------------------------------
#0 line:160 call:Swoole\Error::info	file:/data/php/swoole_framework/framework/libs/Swoole/Swoole.php
#1 line:190 call:Swoole->__construct	file:/data/php/swoole_framework/framework/libs/Swoole/Swoole.php
#2 line:30 call:Swoole::getInstance	file:/data/php/swoole_framework/framework/libs/lib_config.php
#3 line:2 call:require	file:/data/php/swoole_framework/framework/server.php
----------------------------------------------------------------------------------------------------

**Comment by matyhtf** [comment]
需要`define('WEBPATH', $your_src_path);`

**Comment by xuyangbao3** [comment]
good
