### ISSUE TITLE
url中的fragment无法获取

### ISSUE THREAD

**Issue by shakeng** [swoole/framework#85]
例如请求的URL是：/abc/def.html#xyz
代码如下：
$url_arr = parse_url($_SERVER['REQUEST_URI']);
print_r($url_arr)中不见：fragment

追溯sf代码，发现在meta['uri']这一步就没有。请检查一下

**Comment by shakeng** [comment]
原因是浏览器不发送锚点，关闭此Issue

**Comment by lscgzwd** [comment]
not a bug
